# verdict codes: KEEP (basis), EDU, SPLIT (keep part, rest edu), P2 (notice period -> landlord's chosen period + builder check),
# P3 (optional clause + edu row; disclosure owed before signing / on request), FLAG (needs Taylor or statute read)
SL='SERVES_LANDLORD'; CT='CONSTRAINED_TERM'; RD='REQUIRED_DISCLOSURE'
V={
# CO
'late-fee-limit-co':('EDU',None,'cap + 7-day floor restated; 180-day notice is a landlord duty; §38-12-105(1)(c) in-lease disclosure met by late-fee'),
'nsf-fee-limit-co':('EDU',None,'returned-payments sets the fee; not-Rent sentence restates law'),
'habitability-timeline-co':('EDU',None,'restates §38-12-503 duties'),
'landlords-access-co':('SPLIT',SL,'keep access right + 24h written notice; 48h bed-bug rule to edu'),
'bed-bug-disclosure-co':('P3',SL,'owed on request to prospective tenant'),
'utility-submetering-disclosure-co':('SPLIT',RD+': C.R.S. § 6-1-737(4.5)(d)','method must be in lease; fee cap -> landlord chosen fee'),
'security-deposit-return-co':('SPLIT',SL,'keep 30/60-day lease choice; itemization & wear-tear to edu'),
'month-to-month-notice-co-exempt':('P2',SL,'tiers are statutory floors; keep exemption statement'),
'month-to-month-notice-co-covered':('P2',CT,'tiers restated; for-cause restriction to edu'),
'dv-stalking-termination-co':('EDU',None,'tenant right §38-12-402'),
'ev-charging-rights-co':('EDU',None,'tenant right §38-12-601'),
'ev-charging-requirements-co':('KEEP',SL,''),
'ev-charging-shared-area-co':('KEEP',SL,''),
'ev-charging-end-of-tenancy-co':('KEEP',SL,'weak: adds tenant damage duty'),
'subsidy-late-fee-co':('EDU',None,'subsidy protection'),
'subsidy-habitability-proration-co':('EDU',None,'subsidy protection'),
'radon-disclosure-co':('KEEP',RD+': C.R.S. § 38-12-803',''),
'assistance-animal-accommodation-co':('KEEP',SL,'documentation procedure, damage duty, required warning'),
'habitability-notice-co':('SPLIT',SL,'keep written-notice channel; restated warranty/retaliation to edu'),
'utility-allowance-cap-co':('KEEP',CT,''),
'environmental-event-termination-co':('KEEP',SL,'opt-in right only if lease permits'),
'rent-increase-notice-co':('SPLIT',CT,'keep notice period; 12-month cap to edu'),
'source-of-income-statement-co':('KEEP',RD+': C.R.S. § 38-12-801(2.5)','optional (small-landlord exemption); track statutory wording'),
# WY
'dv-safe-homes-wy':('EDU',None,'tenant defense'),
'habitability-baseline-wy':('EDU',None,'landlord duty'),
'renter-duties-wy':('KEEP',SL,''),
'prohibited-acts-renter-wy':('KEEP',SL,''),
'nonrefundable-deposit-notice-wy':('KEEP',RD+': Wyo. Stat. § 1-21-1207',''),
'security-deposit-return-wy':('SPLIT',SL,'keep tenant forwarding-address duty; timeline to edu'),
'utility-deposit-return-wy':('EDU',None,'landlord duty'),
'unpaid-damages-interest-wy':('KEEP',SL,'landlord right'),
'abandoned-property-wy':('KEEP',SL,'landlord disposal right'),
'assistance-animal-accommodation-wy':('KEEP',SL,''),
'periodic-tenancy-notice-wy':('KEEP',CT,'no WY statutory period; lease supplies it'),
'agent-capacity-designation-wy':('KEEP',SL,'opt-out only works in the rental agreement'),
'casualty-termination-wy':('KEEP',SL,'contract choice, no WY statute'),
# KS
'security-deposit-return-ks':('EDU',None,'landlord duty'),
'security-deposit-use-ks':('KEEP',SL,'bars applying deposit to last month'),
'landlord-disclosure-ks':('KEEP',RD+': K.S.A. 58-2551',''),
'habitability-baseline-ks':('EDU',None,'landlord duty'),
'dv-housing-protections-ks':('EDU',None,'tenant right'),
'tenant-duties-ks':('KEEP',SL,''),
'abandoned-property-ks':('KEEP',SL,''),
'late-fee-ks':('KEEP',CT+' | '+SL,''),
'move-in-inventory-ks':('KEEP',SL,'joint inventory documents condition for deductions'),
'possession-delay-ks':('EDU',None,'tenant remedies incl 1.5x'),
'identity-change-liability-ks':('KEEP',SL,''),
'fire-casualty-termination-ks':('EDU',None,'tenant right'),
'pet-policy-ks':('KEEP',SL,''),
'smoke-detectors-ks':('KEEP',SL,'tenant maintenance duty'),
# NE
'security-deposit-return-ne':('EDU',None,'landlord duty'),
'landlord-disclosure-ne':('KEEP',RD+': Neb. Rev. Stat. § 76-1417',''),
'dv-lease-release-ne':('EDU',None,'tenant right'),
'dv-perpetrator-removal-ne':('EDU',None,'tenant right'),
'dv-lockchange-ne':('EDU',None,'tenant right'),
'extended-absence-notice-ne':('KEEP',SL,''),
'abandoned-property-ne':('KEEP',SL,''),
'habitability-baseline-ne':('EDU',None,'landlord duty'),
'tenant-duties-ne':('KEEP',SL,''),
'possession-delay-ne':('EDU',None,'tenant remedies incl 3x'),
'early-termination-ne':('KEEP',SL,''),
'smoke-detector-duty-ne':('KEEP',SL,''),
'tenants-property-insurance-ne':('KEEP',SL,''),
'parking-ne':('KEEP',SL,''),
'storage-space-ne':('KEEP',SL,''),
'pet-policy-ne':('KEEP',SL,''),
'assistance-animal-accommodation-ne':('KEEP',SL,''),
'carbon-monoxide-alarm-duty-ne':('KEEP',SL,'tenant maintenance allocation'),
'casualty-termination-ne':('EDU',None,'tenant right'),
# SD
'security-deposit-return-sd':('EDU',None,'landlord duty + forfeiture'),
'assistance-animal-accommodation-sd':('KEEP',SL,'$1,000 false-claim fee'),
'abandoned-property-sd':('KEEP',SL,''),
'dv-lease-release-sd':('EDU',None,'tenant right'),
'meth-disclosure-sd':('P3',SL,'disclosure owed before tenant is obligated'),
'default-by-tenant-sd':('KEEP',SL,'SDCL 21-16-1(7): lease must specify violation terminates'),
'edu-tenant-termination-causes-sd':('EDU',None,'tenant right (already edu- id)'),
'fire-casualty-rent-abatement-sd':('KEEP',SL,'contract choice'),
'landlords-access-sd':('KEEP',CT,''),
'holdover-sd':('KEEP',SL,'weak: restates renewal presumption'),
'landlord-maintenance-sd':('SPLIT',SL,'keep tenant repair-notice duty; rest edu'),
'pet-policy-sd':('KEEP',SL,''),
# ND
'security-deposit-return-nd':('EDU',None,'landlord duty'),
'assistance-animal-accommodation-nd':('KEEP',SL,''),
'abandoned-property-nd':('KEEP',SL,''),
'termination-by-death-nd':('EDU',None,'estate right'),
'smoke-detector-duty-nd':('KEEP',SL,''),
'fire-casualty-termination-nd':('EDU',None,'tenant right'),
'tenant-maintenance-nd':('KEEP',SL,''),
'landlord-maintenance-nd':('SPLIT',SL,'keep tenant written repair notice; rest edu'),
'dv-lease-release-nd':('EDU',None,'tenant right'),
'termination-notice-nd':('P2',CT,'statutory one-month period restated'),
'lease-notice-initial-requirement-nd':('KEEP',RD+': N.D.C.C. § 47-16-15(4)',''),
'landlords-access-nd':('KEEP',CT+' | '+SL,''),
'tenant-notice-of-adverse-proceeding-nd':('KEEP',SL,''),
# MN
'landlords-access-mn':('KEEP',CT+' | '+SL,''),
'security-deposit-return-mn':('EDU',None,'landlord duty'),
'termination-death-of-tenant-mn':('KEEP',SL,'weak: includes landlord termination right'),
'termination-infirmity-mn':('EDU',None,'tenant right'),
'abandoned-property-mn':('KEEP',SL,''),
'utility-apportionment-mn':('SPLIT',SL,'keep estimated-final-bill right and method; caps/no-disconnect to edu'),
'tenants-property-insurance-mn':('KEEP',SL,''),
'pet-policy-mn':('KEEP',SL+' | '+RD+': Minn. Stat. § 504B.113 subd. 3(b)',''),
'parking-mn':('KEEP',SL,''),
'storage-space-mn':('KEEP',SL,''),
'services-utilities-provided-mn':('KEEP',SL,''),
'habitability-baseline-mn':('SPLIT',SL,'keep tenant written repair notice; rest edu'),
'assistance-animal-accommodation-mn':('KEEP',SL,''),
'possession-delay-mn-new-construction':('EDU',None,'landlord duty / tenant options'),
'smoke-detector-duty-mn':('KEEP',SL,''),
'carbon-monoxide-alarm-duty-mn':('KEEP',SL,''),
'dv-lease-termination-mn':('EDU',None,'tenant right'),
'foreclosure-disclosure-mn':('P3',SL,'written notice owed before entering lease'),
'initial-final-inspection-mn':('P3',SL,'inspection-option notice owed at commencement'),
'landlord-disclosure-mn':('KEEP',RD+': Minn. Stat. § 504B.181',''),
'deposit-last-month-rent-mn':('KEEP',SL,''),
'fire-casualty-termination-mn':('EDU',None,'tenant right'),
'cash-rent-receipt-mn':('EDU',None,'landlord duty'),
'lease-copy-receipt-mn':('KEEP',SL,'statute blesses in-lease acknowledgment'),
'prelease-deposit-application-mn':('EDU',None,'landlord duty'),
'utility-billing-schedule-mn':('KEEP',RD+': Minn. Stat. § 504B.215',''),
'cold-weather-vacate-notice-mn':('KEEP',SL,''),
}
