SL='SERVES_LANDLORD'; CT='CONSTRAINED_TERM'; RD='REQUIRED_DISCLOSURE'
V={
# OH
'security-deposit-interest-oh':('EDU',None,'landlord interest duty'),
'security-deposit-return-oh':('SPLIT',SL,'keep forwarding-address duty and its consequence; timeline to edu'),
'holdover-oh':('KEEP',CT,'stipulated rate'),
'landlord-identity-oh':('KEEP',RD+': R.C. 5321.18',''),
'flag-display-oh':('EDU',None,'tenant right'),
'repair-escrow-exemption-notice-oh':('KEEP',RD+': R.C. 5321.07(C)','exemption applies only if landlord gives notice'),
'sex-offender-occupancy-oh':('KEEP',SL,''),
'assistance-animal-accommodation-oh':('KEEP',SL,''),
'landlord-maintenance-oh':('EDU',None,'landlord-duty restatement; Taylor 2026-09-29: apply the rule (reverses the 2026-09-28 add)'),
'fire-casualty-termination-oh':('EDU',None,'tenant right'),
'termination-notice-oh':('P2',CT,'statutory periods restated'),
# CA
'late-fee-safe-harbor-ca':('KEEP',CT+' | '+SL,'liquidated damages must be agreed'),
'nsf-fee-limit-ca':('SPLIT',CT,'keep fee placeholder; cap and tenant defenses to edu'),
'month-to-month-notice-ca':('P2',CT,'notice periods restated'),
'bed-bug-disclosure-ca':('P3',SL,'Civ. Code 1954.603 written notice to prospective tenants; keep reporting procedure'),
'meth-disclosure-ca':('P3',SL,'written notice before signing'),
'flood-disclosure-ca':('KEEP',RD+': Gov. Code § 8589.45',''),
'sex-offender-registry-notice-ca':('KEEP',RD+': Civ. Code § 2079.10a',''),
'tpa-notice-ca':('KEEP',RD+': Civ. Code §§ 1946.2(f), 1947.12(g)',''),
'tpa-exemption-notice-ca':('KEEP',RD+': Civ. Code § 1946.2(e)(8)(B)(iii)',''),
'owner-move-in-reservation-ca':('KEEP',SL,'opt-in right'),
'security-deposit-cap-ca':('EDU',None,'cap to edu; Taylor 2026-09-29: tag the shared security-deposit-use for CA after checking it against Civ. Code § 1950.5(b), so CA keeps a deposit amount and use clause'),
'security-deposit-return-ca':('SPLIT',SL,'keep lease-choice deduction for personal property; rest edu'),
'rent-increase-cap-ca':('SPLIT',RD+': Civ. Code § 1947.12','keep concession listing; cap to edu'),
'notice-service-fee-ban-ca':('EDU',None,'landlord prohibition'),
'bed-bug-cooperation-ca':('KEEP',SL,'tenant duty'),
'assistance-animal-accommodation-ca':('KEEP',SL,''),
'landlord-entry-ca':('KEEP',CT+' | '+SL,''),
'accommodation-request-rights-ca':('EDU',None,'tenant right'),
'reasonable-modification-ca':('EDU',None,'tenant right'),
'repair-and-deduct-ca':('EDU',None,'tenant remedy'),
'owner-identity-disclosure-ca':('KEEP',RD+': Civ. Code § 1962',''),
'rent-increase-notice-ca':('EDU',None,'landlord duty, statute sets periods'),
'tenant-maintenance-obligations-ca':('KEEP',SL,''),
'payment-methods-ca':('SPLIT',SL,'keep accepted methods and cash-only right; restated duties to edu'),
'political-signs-ca':('EDU',None,'tenant right'),
'waterbed-ca':('KEEP',SL,'weak: landlord insurance/deposit/inspection rights'),
'rent-payment-ca':('KEEP',SL,''),
'existing-condition-ca':('KEEP',SL,''),
'services-utilities-provided-ca':('KEEP',SL,''),
'common-area-use-ca':('KEEP',SL,''),
'pet-policy-ca':('KEEP',SL,''),
'due-at-signing-ca':('SPLIT',SL,'trim cap sentence to edu'),
'early-termination-ca':('KEEP',SL,'opt-in 1951.2 measure'),
'continue-lease-remedy-ca':('KEEP',SL,'opt-in 1951.4 form'),
'no-sublet-assign-ca':('KEEP',SL,''),
'no-sublet-assign-discretion-ca':('KEEP',SL,''),
'dv-lease-termination-ca':('EDU',None,'tenant right'),
'emergency-assistance-right-ca':('EDU',None,'tenant right'),
'alarm-duties-ca':('KEEP',SL,'tenant duties + entry right'),
'ev-charging-ca':('KEEP',SL,'tenant request conditions and costs'),
'casualty-termination-ca':('EDU',None,'tenant right'),
'stove-refrigerator-ca':('SPLIT',RD+': Civ. Code § 1941.1(a)(11)(B)','keep tenant-supplied fridge acknowledgment; duty to edu'),
'immigration-status-inquiry-ca':('EDU',None,'landlord prohibition'),
'auto-renewal-formatting-ca':('KEEP',RD+': Civ. Code § 1945.5',''),
'security-devices-ca':('SPLIT',SL,'keep tenant notice duty; landlord duty to edu'),
'tenant-use-rights-ca':('EDU',None,'tenant rights'),
'pest-control-notice-ca':('EDU',None,'landlord notice duties'),
'ordnance-demolition-meter-disclosures-ca':('P3',SL,'written disclosure before execution'),
'disaster-duties-ca':('EDU',None,'landlord duties'),
'lock-change-non-cotenant-ca':('EDU',None,'tenant right'),
'internet-billing-optout-ca':('EDU',None,'tenant right'),
'unbundled-parking-ca':('SPLIT',RD+': Civ. Code § 1947.1','keep parking-not-included statement and revocation right; rest edu'),
'military-lease-termination-ca':('EDU',None,'tenant right'),
'possession-delay-ca':('KEEP',SL,''),
'landlord-maintenance-ca':('KEEP',SL,'allocation, same as generic'),
'water-submeter-disclosure-ca':('P3',SL,'disclosure before execution'),
'mold-booklet-disclosure-ca':('P3',SL,'booklet before signing; keep tenant notice duty'),
}
