SL='SERVES_LANDLORD'; CT='CONSTRAINED_TERM'; RD='REQUIRED_DISCLOSURE'
K=lambda b,n='':('KEEP',b,n)
V={
# NV
'foreclosure-disclosure-nv':('P3',SL,'written disclosure before entering lease'),
'rent-single-figure-nv':K(RD+': NRS 118A.200'),
'late-fee-nv':('SPLIT',CT+' | '+RD+': NRS 118A.200(3)','keep fee; 3-day floor and 5% cap to edu'),
'security-deposit-cap-nv':('SPLIT',SL,'keep surety-bond option; cap to edu'),
'security-deposit-return-nv':('SPLIT',SL,'keep nonrefundable cleaning charge statement and forwarding address; rest edu'),
'move-in-inventory-nv':K(RD+': NRS 118A.200(3)(k)'),
'owner-identity-disclosure-nv':K(RD+': NRS 118A.260'),
'possession-delay-nv':('EDU',None,'tenant remedies'),
'tenant-maintenance-nv':K(SL),
'pet-policy-nv':K(SL+' | '+RD+': NRS 118A.200(3)(c)'),
'payment-methods-nv':K(CT+' | '+RD+': NRS 118A.200'),
'returned-payments-nv':K(CT+' | '+RD+': NRS 118A.200(3)(g)'),
'rent-increase-notice-nv':('SPLIT',SL,'keep no-increase-during-term; notice period to edu'),
'casualty-termination-nv':('SPLIT',SL,'keep landlord termination right; tenant rights to edu'),
'abandoned-property-nv':K(SL),
'dv-lease-termination-nv':('EDU',None,'tenant right'),
'infirmity-death-termination-nv':('EDU',None,'tenant right'),
'flag-display-nv':K(RD+': NRS 118A.200(3)(n)'),
'religious-display-nv':K(RD+': NRS 118A.200(3)(o)'),
'nuisance-reporting-nv':K(RD+': NRS 118A.200(3)(l)-(m)'),
'sfr-occupancy-disclosure-nv':K(RD+': NRS 118A.200(4)'),
'property-tax-rent-disclosure-nv':('EDU',None,'annual landlord statement duty'),
'smoke-detector-duty-nv':K(SL),
'children-occupancy-nv':K(RD+': NRS 118A.200(3)(c)'),
'required-fees-nv':K(RD+': NRS 118A.200(3)'),
'tenant-repair-agreement-nv':K(SL,'opt-in'),
'designated-repairer-nv':K(SL,'opt-in'),
# TX
'late-fee-safe-harbor-tx':('SPLIT',CT,'keep fee and liquidated-damages agreement; floor, cap and statement duty to edu'),
'nsf-fee-limit-tx':('SPLIT',CT,'keep fee; $30 cap to edu'),
'habitability-timeline-tx':K(RD+': Tex. Prop. Code § 92.056(g)'),
'flood-disclosure-tx':K(RD+': Tex. Prop. Code § 92.0135'),
'utility-submetering-disclosure-tx':('SPLIT',RD+': 16 Tex. Admin. Code § 24.279','keep disclosures; charge limits to edu'),
'keys-tx':K(SL),
'acceptable-payment-methods-tx':K(CT),
'security-deposit-return-tx':('SPLIT',SL,'keep forwarding-address and e-mail designation; rest edu'),
'deposit-surrender-notice-tx':K(SL,'opt-in'),
'deposit-last-month-rent-tx':K(SL),
'tenant-repair-agreement-tx':K(SL,'opt-in'),
'security-devices-tx':K(SL,'bold statement extends cure time; written-request rule'),
'smoke-alarm-tx':K(SL,'remedies need the bold notice'),
'early-termination-rights-statement-tx':K(RD+': Tex. Prop. Code §§ 92.016(f), 92.0161(g)'),
'emergency-phone-tx':('P3',SL,'statute requires the number, not in the lease'),
'owner-management-disclosure-tx':K(SL,'inclusion in lease is full compliance'),
'casualty-loss-tx':K(SL,'weak: mutual termination; insurance-proceeds timing'),
'lockout-rent-delinquency-tx':K(SL,'opt-in'),
'parking-rules-tx':K(RD+': Tex. Prop. Code § 92.0131'),
'electric-submeter-interruption-tx':K(SL,'opt-in'),
'deceased-tenant-contact-tx':K(SL),
'landlord-lien-tx':K(SL,'opt-in'),
'electronic-notice-consent-tx':K(SL,'opt-in'),
'notice-to-vacate-period-tx':K(CT),
'parking-vehicle-rules-tx':K(SL),
'electric-submeter-disclosure-tx':K(SL),
'abandoned-property-tx':K(SL,'opt-in definition'),
# NJ
'security-deposit-interest-nj':('EDU',None,'landlord duties'),
'security-deposit-return-nj':('SPLIT',SL,'keep deposit amount; cap and return duties to edu'),
'late-fee-nj':('SPLIT',CT,'keep fee; senior grace rule to edu'),
'acceptable-payment-methods-nj':('SPLIT',CT,'keep methods; receipt and post-warrant duties to edu'),
'holdover-nj':('SPLIT',SL,'keep double-rent remedies; Anti-Eviction restatement to edu'),
'surrender-end-of-term-nj':('SPLIT',SL,'keep surrender duties; property procedure to edu'),
'pet-policy-nj':K(SL),
'window-guard-notice-nj':K(RD+': N.J.A.C. 5:10-27.1'),
'flood-insurance-lease-notice-nj':K(RD+': N.J.S.A. 46:8-50(c)'),
'flood-risk-disclosure-nj':K(RD+': N.J.S.A. 46:8-50'),
'truth-in-renting-statement-nj':K(SL,'acknowledgment of required delivery'),
'landlord-registration-disclosure-nj':K(SL,'acknowledgment of required delivery'),
'lead-safe-certification-nj':K(RD+': N.J.S.A. 52:27D-437.16'),
'conversion-statement-nj':K(RD+': N.J.S.A. 2A:18-61.9'),
'rent-control-exemption-notice-nj':K(RD+': N.J.S.A. 2A:42-84.1 et seq.'),
'tenant-supplied-heat-nj':K(SL,'written agreement shifts heat'),
'right-of-reentry-nj':K(SL,'opt-in'),
'default-by-tenant-nj':K(SL),
'assistance-animal-accommodation-nj':K(SL),
'returned-payments-nj':K(CT),
'steam-radiator-cover-notice-nj':K(RD+': N.J.S.A. 52:27D-198.20'),
'private-well-test-results-nj':('SPLIT',SL,'keep acknowledgment; testing duty to edu'),
'casualty-nj':('EDU',None,'restates statutory abatement'),
# FL
'nsf-fee-limit-fl':K(CT,'fee stated as the term'),
'flood-disclosure-fl':K(RD+': Fla. Stat. § 83.50(2)'),
'security-deposit-return-fl':('SPLIT',CT,'keep holding-method choice; restated duties to edu'),
'security-deposit-notice-fl':K(RD+': Fla. Stat. § 83.49(2)'),
'fee-in-lieu-of-deposit-fl':K(SL,'opt-in'),
'landlords-access-fl':K(SL),
'early-termination-fl':K(SL),
'early-termination-addendum-fl':K(SL,'opt-in'),
'end-of-term-notice-fl':K(SL,'opt-in'),
'electronic-notice-addendum-fl':K(SL,'opt-in'),
'landlord-address-disclosure-fl':K(RD+': Fla. Stat. § 83.50(1)'),
'pet-policy-fl':K(SL),
'flotation-bedding-fl':K(SL),
'casualty-damage-fl':('EDU',None,'tenant right'),
'abandoned-property-release-fl':K(SL,'opt-in'),
'default-by-tenant-fl':K(SL),
'radon-disclosure-fl':K(RD+': Fla. Stat. § 404.056(5)'),
'assistance-animal-accommodation-fl':K(SL),
'common-area-use-fl':K(SL),
'maintenance-allocation-fl':K(SL,'opt-in'),
'no-liens-fl':K(SL,'opt-in'),
'association-approval-fl':K(SL),
# AZ
'security-deposit-return-az':('SPLIT',SL,'keep application right and tenant demand; timeline to edu'),
'security-deposit-cap-az':('EDU',None,'cap'),
'nonrefundable-fees-az':K(RD+': A.R.S. § 33-1321(B)'),
'move-in-inspection-az':('EDU',None,'landlord duty'),
'landlords-access-az':K(SL),
'possession-delay-az':('EDU',None,'tenant remedies'),
'late-fee-az':K(CT+' | '+SL),
'pet-policy-az':K(SL),
'authorized-person-contact-az':K(SL,'opt-in'),
'landlord-disclosure-az':K(RD+': A.R.S. § 33-1322'),
'dv-lease-termination-az':('EDU',None,'tenant right'),
'bedbug-obligations-az':K(SL),
'utility-billing-disclosure-az':K(RD+': A.R.S. § 33-1314.01'),
'foreclosure-notice-az':('P3',SL,'notice owed before lease'),
'pool-safety-notice-az':K(SL,'acknowledgment of required notice'),
'maintenance-allocation-az':K(SL,'opt-in'),
'casualty-termination-az':('EDU',None,'tenant right'),
'crime-free-addendum-az':K(SL),
'smoke-detector-duty-az':K(SL,'written notice shifts duty to tenant'),
# GA
'security-deposit-cap-ga':('EDU',None,'cap'),
'security-deposit-return-ga':('SPLIT',SL,'keep sign-or-dissent duty; rest edu'),
'security-deposit-escrow-ga':K(RD+': O.C.G.A. § 44-7-31'),
'move-in-damage-list-ga':K(SL,'signed list is conclusive'),
'landlord-disclosure-ga':K(RD+': O.C.G.A. § 44-7-3'),
'flood-disclosure-ga':('P3',SL,'separate notice before signing'),
'assistance-animal-accommodation-ga':K(SL),
'dv-lease-termination-ga':('EDU',None,'tenant right'),
'rent-escalation-ga':K(SL,'opt-in'),
'serious-misconduct-prohibition-ga':K(SL),
'holdover-rate-ga':K(CT),
'casualty-termination-ga':K(SL,'contract choice'),
# NC
'late-fee-limit-nc':('SPLIT',CT,'keep fee; cap and rules to edu'),
'security-deposit-use-nc':K(SL),
'security-deposit-cap-nc':('EDU',None,'cap'),
'security-deposit-holding-nc':K(RD+': N.C. Gen. Stat. § 42-50'),
'security-deposit-return-nc':('EDU',None,'landlord duty'),
'eviction-fees-nc':K(SL,'opt-in'),
'partial-payment-nonwaiver-nc':K(SL,'opt-in'),
'criminal-activity-nc':K(SL),
'assistance-animal-accommodation-nc':K(SL),
'pet-policy-nc':K(SL),
'dv-lease-termination-nc':('EDU',None,'tenant right'),
'casualty-termination-nc':K(SL,'contract choice'),
'renters-insurance-nc':K(SL),
'emergency-contact-nc':K(SL),
'smoke-co-alarms-nc':K(SL),
'utility-billing-nc':K(SL,'opt-in'),
'periodic-tenancy-notice-nc':K(CT),
'holdover-rate-nc':K(CT),
# SC
'security-deposit-return-sc':('SPLIT',SL,'keep forwarding-address duty; rest edu'),
'security-deposit-standards-sc':('P3',SL,'statement before signing'),
'landlord-disclosure-sc':K(RD+': S.C. Code Ann. § 27-40-420'),
'nonpayment-notice-sc':K(SL,'opt-in'),
'possession-delay-sc':('EDU',None,'tenant remedies'),
'pet-policy-sc':K(SL),
'assistance-animal-accommodation-sc':K(SL),
'dv-lease-termination-sc':('EDU',None,'tenant right'),
'casualty-termination-sc':('EDU',None,'tenant right'),
'casualty-landlord-termination-sc':K(SL,'opt-in'),
'holdover-rate-sc':K(CT),
'periodic-services-entry-sc':K(SL,'opt-in'),
'tenant-repair-agreement-sc':K(SL,'opt-in'),
'appliances-excluded-sc':K(SL,'opt-in'),
'smoke-detectors-sc':K(SL),
'meter-conservation-charge-notice-sc':K(RD+': S.C. Code Ann. § 58-37-50(H)(3)'),
'abandoned-property-sc':K(SL),
# TN
'late-fee-limit-tn':('SPLIT',CT,'keep fee; grace and cap to edu'),
'late-fee-tn-other':K(CT),
'security-deposit-return-tn-act':('SPLIT',SL,'keep account-location statement; rest edu'),
'security-deposit-return-tn-other':('SPLIT',SL,'keep forwarding-address duty; rest edu'),
'landlords-access-tn-act':K(SL),
'landlords-access-tn-other':K(SL),
'nonpayment-notice-waiver-tn':K(SL,'opt-in'),
'landlord-disclosure-tn':K(RD+': Tenn. Code Ann. § 66-28-302'),
'renters-insurance-advisory-tn':K(RD+': prescribed advisory (Tenn. Code Ann. § 66-28-201(a))'),
'assistance-animal-accommodation-tn':K(SL),
'dv-lease-termination-tn':('EDU',None,'tenant right'),
'casualty-termination-tn':('SPLIT',SL,'keep landlord termination right; tenant rights to edu'),
'holdover-rate-tn':K(CT),
'periodic-tenancy-notice-tn':('P2',CT,'statutory periods restated'),
'abandoned-property-tn':K(SL),
'tenant-repair-agreement-tn':K(SL,'opt-in'),
'utility-transfer-tn':K(SL,'opt-in'),
'electronic-notice-tn':K(SL,'opt-in'),
'smoke-alarms-tn':K(SL),
'firearm-carry-rules-tn':K(SL),
'pet-policy-tn':K(SL),
'eviction-service-party-tn':K(SL,'opt-in'),
'possession-bond-tn':K(SL,'opt-in'),
'household-goods-lien-tn':K(SL,'opt-in'),
# VA
'late-fee-limit-va':('SPLIT',CT,'keep fee (must be in lease to be charged); cap to edu'),
'meth-disclosure-va':('P3',SL,'disclosure before signing'),
'mold-disclosure-va':K(SL,'report deemed correct unless tenant objects'),
'returned-payments-va':('SPLIT',CT,'keep fee; $50 cap to edu'),
'acceptable-payment-methods-va':('SPLIT',CT,'keep methods; receipt and fee rules to edu'),
'acceptable-payment-methods-va-small':K(SL,'opt-in'),
'security-deposit-return-va':('EDU',None,'cap and landlord duties'),
'expedited-deposit-disposition-va':K(SL,'opt-in'),
'move-in-inspection-va':K(SL,'report deemed correct unless tenant objects'),
'defective-drywall-disclosure-va':('P3',SL,'disclosure before signing'),
'military-air-zone-disclosure-va':('P3',SL,'disclosure before signing'),
'tenant-rights-statement-va':K(SL,'acknowledgment of required statement'),
'fee-disclosure-statement-va':K(RD+': Va. Code Ann. § 55.1-1204'),
'landlord-disclosure-va':K(RD+': Va. Code Ann. § 55.1-1216'),
'nonresident-owner-agent-va':K(RD+': Va. Code Ann. § 55.1-1211'),
'renters-insurance-notice-va':K(RD+': Va. Code Ann. § 55.1-1206(D)'),
'damage-insurance-va':K(SL),
'landlords-access-va':K(SL),
'no-sublet-assign-va':K(SL),
'holdover-rate-va':K(CT,'opt-in'),
'redemption-rights-va':('EDU',None,'tenant right'),
'redemption-limit-va-small':K(SL,'opt-in'),
'renewal-notice-va':('EDU',None,'landlord duty'),
'renewal-notice-va-small':K(CT),
'portable-solar-va':('EDU',None,'tenant right'),
'portable-solar-va-small':K(SL,'opt-in'),
'tenant-duties-va':K(SL),
'smoke-co-alarms-va':K(SL),
'dv-lease-termination-va':('EDU',None,'tenant right'),
'military-lease-termination-va':('EDU',None,'tenant right'),
'abandoned-property-va':K(SL),
'casualty-termination-va':('SPLIT',SL,'keep landlord termination right; tenant rights to edu'),
'periodic-tenancy-notice-va':K(CT,'lease may set the period'),
'emergency-contact-va':K(SL),
'foreclosure-notice-va':('EDU',None,'landlord duty, tenant remedy'),
'utility-billing-va':K(SL+' | '+RD+': Va. Code Ann. § 55.1-1212','opt-in'),
'tenant-repair-agreement-va':K(SL,'opt-in'),
'assistance-animal-accommodation-va':K(SL),
'pet-policy-va':K(SL),
'electronic-notices-va':K(SL,'opt-in'),
'homestead-waiver-va':K(SL,'opt-in'),
# AL
'security-deposit-return-al':('SPLIT',SL,'keep forwarding-address duty; rest edu'),
'security-deposit-cap-al':('SPLIT',RD+': Ala. Code § 35-9A-201(a)','keep additional-security statement; cap to edu (confirm the statute requires the statement in the lease)'),
'landlord-disclosure-al':K(RD+': Ala. Code § 35-9A-202'),
'default-by-tenant-al':K(SL),
'landlords-access-al':K(SL),
'possession-delay-al':('EDU',None,'tenant remedies'),
'pet-policy-al':K(SL),
'assistance-animal-accommodation-al':K(SL),
'casualty-termination-al':('EDU',None,'tenant right'),
'casualty-landlord-termination-al':K(SL,'opt-in'),
'holdover-rate-al':K(CT),
'extended-absence-notice-al':K(SL,'opt-in'),
'tenant-repair-agreement-al':K(SL,'opt-in'),
'abandoned-property-al':K(SL),
'sex-offender-statement-al':K(RD+': Ala. Code § 13A-11-204(a)'),
'exemption-waiver-al':K(SL,'opt-in'),
# PA
'security-deposit-return-pa':('SPLIT',SL,'keep forwarding-address duty; forfeiture and double damages to edu'),
'security-deposit-holding-pa':('SPLIT',RD+': 68 P.S. § 250.511b(a)','keep institution notice; interest duty to edu'),
'abandoned-property-pa':K(SL,'lease controls over statute'),
'notice-to-quit-waiver-pa':K(SL,'opt-in'),
'consumer-restrictions-statement-pa':K(RD+': 73 P.S. § 2205(d)'),
'assistance-animal-accommodation-pa':K(SL),
'pet-policy-pa':K(SL),
'carbon-monoxide-alarm-duty-pa':K(SL,'weak: tenant replacement allocation'),
'holdover-rate-pa':K(CT),
'casualty-termination-pa':K(SL,'contract choice'),
'periodic-tenancy-notice-pa':K(CT),
}
