# Builds lease-clause-topics.md, the topic reference every state pass works
# through (SOP rules 27 and 36). Generated, never edited by hand:
#   - topics come from the `topic_key` of every active row in lease-clauses.csv,
#     so a topic exists once any state has a clause or education row for it;
#   - the questions under each topic come from topic-questions.csv (first
#     built from the retired checklist's topic tables, 2026-09-29). A key
#     starting "NEW:" is a topic no state has a row for yet.
# To add a question: append a row to topic-questions.csv and re-run.
#
# Usage (from the repo root):
#   python3 scripts/clause-library/build-topic-reference.py
import csv, collections, re

CSV = "lease-clauses.csv"
QUESTIONS = "scripts/clause-library/topic-questions.csv"
OUT = "lease-clause-topics.md"
GROUP_ORDER = [
    "Rent & Payment", "Security Deposit", "Tenant Responsibilities",
    "Landlord Responsibilities", "Access & Entry", "Default & Termination",
    "Notices & General", "Pets", "Parking & Storage", "Rules & Regulations",
    "Disclosures", "Other / Miscellaneous",
]

rows = [r for r in csv.DictReader(open(CSV, newline="", encoding="utf-8")) if r["is_active"] == "TRUE"]
states_of = lambda r: [s.strip() for s in re.split("[;,]", r["states"]) if s.strip()]
all_states = sorted({s for r in rows for s in states_of(r)})

by_key = collections.defaultdict(list)
for r in rows:
    by_key[r["topic_key"]].append(r)

questions = collections.defaultdict(list)
for q in csv.DictReader(open(QUESTIONS, newline="", encoding="utf-8")):
    questions[q["topic_key"]].append(q["question"])

unknown = [k for k in questions if not k.startswith("NEW:") and k not in by_key]
if unknown:
    raise SystemExit(f"FAIL - topic-questions.csv names keys with no active row: {', '.join(sorted(unknown))}")

def name(key):
    return key.replace("-", " ").capitalize()

def group_of(key):
    g = collections.Counter(r["group"] for r in by_key[key]).most_common(1)[0][0]
    return g if g in GROUP_ORDER else "Other / Miscellaneous"

sections = collections.defaultdict(list)
for key in by_key:
    sections[group_of(key)].append(key)

out = []
out.append("# Topic reference\n")
out.append("**Generated by `scripts/clause-library/build-topic-reference.py`. Don't edit by hand.** "
           "Every subject the clause library covers, one entry per `topic_key`, grouped the way a lease is. "
           "A new state answers every topic here (SOP rules 27 and 36): a clause, an education row "
           "(including a confirmed absence), or a recorded reason the topic doesn't apply. The questions "
           "under a topic are things earlier states found worth checking; they are prompts, not a complete list.\n")
out.append(f"{len(by_key)} topics from {len(rows)} active rows across {len(all_states)} states. "
           "\"Rows in N states\" counts states with any row on the topic.\n")
out.append("To add a topic, write a row with a new `topic_key`. To add a question, list it under "
           "\"Proposed topic questions\" in the state log; Claude Code adds it here at sync.\n")

new_keys = sorted(k for k in questions if k.startswith("NEW:"))
if new_keys:
    out.append("\n## Topics no state has a row for yet\n")
    out.append("Found by earlier states but never given a row. Check each for every state, and write a row "
               "(clause or education) where the state has law on it.\n")
    for k in new_keys:
        out.append(f"\n### {name(k[4:])} (`{k[4:]}`)\n")
        for q in questions[k]:
            out.append(f"- {q}")

for g in GROUP_ORDER:
    keys = sorted(sections.get(g, []))
    if not keys:
        continue
    out.append(f"\n## {g}\n")
    for k in keys:
        n = len({s for r in by_key[k] for s in states_of(r)})
        out.append(f"\n### {name(k)} (`{k}`)\n")
        out.append(f"Rows in {n} states.")
        for q in questions.get(k, []):
            out.append(f"- {q}")

open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"ok - wrote {OUT}: {len(by_key)} topics, {len(new_keys)} without rows, "
      f"{sum(len(v) for v in questions.values())} questions")
