-- AlterTable
ALTER TABLE "Occupant" ALTER COLUMN "bodyBuild" DROP DEFAULT,
ALTER COLUMN "eyeColor" DROP DEFAULT,
ALTER COLUMN "hairColor" DROP DEFAULT,
ALTER COLUMN "sex" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Tenant" ALTER COLUMN "bodyBuild" DROP DEFAULT,
ALTER COLUMN "eyeColor" DROP DEFAULT,
ALTER COLUMN "hairColor" DROP DEFAULT,
ALTER COLUMN "sex" DROP DEFAULT;
